version: "3"

tasks:
  gen:ts:
    desc: "Generate TypeScript from konst.json"
    cmds:
      - go run . -i ./example/konst.json -o gen/konst.ts -f

  gen:go:
    desc: "Generate TypeScript from konst.json"
    cmds:
      - go run . -i ./example/konst.json -o gen/konst.go -f

  gen:all:
    desc: "Generate both TypeScript and Go from konst.json"
    deps:
      - gen:ts
      - gen:go

  gen:dir:ts:
    desc: "Generate TypeScript from konst.json"
    cmds:
      - go run . -i ./example/multi -o gen/multi/ts -f -m=ts

  gen:dir:go:
    desc: "Generate TypeScript from konst.json"
    cmds:
      - go run . -i ./example/multi -o gen/multi/go -f -m=go

  gen:dir:all:
    desc: "Generate both TypeScript and Go from multi file"
    deps:
      - gen:dir:ts
      - gen:dir:go
