version: "3"

tasks:
  gen:ts:
    desc: "Generate TypeScript from konst.json"
    cmds:
      - go run . -i ./example/konst.json -o gen/single -m ts -f

  gen:go:
    desc: "Generate Go from konst.json"
    cmds:
      - go run . -i ./example/konst.json -o gen/single -m go -f

  gen:all:
    desc: "Generate both TypeScript and Go from konst.json"
    deps:
      - gen:ts
      - gen:go

  gen:dir:ts:
    desc: "Generate TypeScript from multi directory"
    cmds:
      - go run . -i ./example/multi -o gen/multi/ts -m ts -f

  gen:dir:go:
    desc: "Generate Go from multi directory"
    cmds:
      - go run . -i ./example/multi -o gen/multi/go -m go -f

  gen:dir:all:
    desc: "Generate both TypeScript and Go from multi file"
    deps:
      - gen:dir:ts
      - gen:dir:go
